services:
  edugame:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ./src/:/app/
      - ./dist/:/app/81dcb9af-f6f5-5ecb-bac7-ad5caf4fdc06/
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - 'traefik.http.routers.edugame-web.rule=Host(`teamgatitos.byancode.com`)'
      - traefik.http.routers.edugame-web.entrypoints=web
      - traefik.http.routers.edugame-web.middlewares=redirect-to-https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - 'traefik.http.routers.edugame-websecure.rule=Host(`teamgatitos.byancode.com`)'
      - traefik.http.routers.edugame-websecure.entrypoints=websecure
      - traefik.http.routers.edugame-websecure.tls=true
      - traefik.http.routers.edugame-websecure.service=edugame
      - traefik.http.services.edugame.loadbalancer.server.port=8080
    command: ["python3", "-m", "http.server", "8080", "--bind", "0.0.0.0"]
networks:
  proxy:
    external: true
